apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 4499  # Container ka internal port
  type: LoadBalancer  # Service ko external access ke liye expose karega
